version: '3.9'

services:
  dmit-facturador-landing-page:
    build:
      context: ./dmit-facturador-landing-page
    container_name: dmit-facturador-landing-page
    ports:
      - "3000:3000" # Exponer el puerto 3000 solo si quieres probar localmente
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    command: sh -c "rm -f /tmp/nitro/*.sock && npm run dev"

  dmit-vue-app:
    build:
      context: ./dmit-vue-app
    container_name: dmit-vue-app
    ports:
      - "5173:5173" # Exponer el puerto 3001 solo si quieres probar localmente
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5173" ]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Exponer el puerto 80 para acceder al dominio
      - "443:443" # Exponer el puerto 443 para acceder al dominio
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Configuración de Nginx
      - ./ssl-certificates:/etc/letsencrypt
    depends_on:
      dmit-facturador-landing-page:
        condition: service_healthy
      dmit-vue-app:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
